export CUDA_VISIBLE_DEVICES=2,3,4,5,6,7
export DATA_DIR='data/medcase'
export RETRIEVER_PORT="${RETRIEVER_PORT:-8000}"

WAND_PROJECT='Search-R1'

export BASE_MODEL="Med-Qwen2.5-3B-Instruct-SFT-merged"
#"Med-Qwen2.5-3B-Instruct-SFT"
export EXPERIMENT_NAME="med-search-r1-grpo-qwen2.5-3b-Instruct"

# export BASE_MODEL='meta-llama/Llama-3.2-3B'
# export EXPERIMENT_NAME=nq-search-r1-grpo-llama3.2-3b-em
# export BASE_MODEL='meta-llama/Llama-3.2-3B-Instruct'
# export EXPERIMENT_NAME=nq-search-r1-grpo-llama3.2-3b-it-em
# export BASE_MODEL='meta-llama/Llama-3.1-8B'
# export EXPERIMENT_NAME=nq-search-r1-grpo-llama3.1-8b-em
# export BASE_MODEL='meta-llama/Llama-3.1-8B-Instruct'
# export EXPERIMENT_NAME=nq-search-r1-grpo-llama3.1-8b-it-em
# export BASE_MODEL='Qwen/Qwen2.5-3B-Instruct'
# export EXPERIMENT_NAME=nq-search-r1-grpo-qwen2.5-3b-it-em
# export BASE_MODEL='Qwen/Qwen2.5-7B'
# export EXPERIMENT_NAME=nq-search-r1-grpo-qwen2.5-7b-em
# export BASE_MODEL='Qwen/Qwen2.5-7B-Instruct'
# export EXPERIMENT_NAME=nq-search-r1-grpo-qwen2.5-7b-it-em
# set -x
export VLLM_ATTENTION_BACKEND=XFORMERS # vllm + qwen2-7b with flash_attn has some issues

# max_prompt_length = (config['training']['max_start_length'] + config['training']['max_response_length'] * (config['training']['max_turns'] - 1) + config['training']['max_obs_length'] * config['training']['max_turns'])

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo_format \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet \
    data.train_data_num=null \
    data.val_data_num=null \
    data.train_batch_size=32 \
    data.val_batch_size=32 \
    data.max_prompt_length=2048 \
    data.max_response_length=512 \
    data.max_start_length=2048 \
    data.max_obs_length=512 \
    data.shuffle_train_dataloader=True \
    algorithm.adv_estimator=grpo \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285 \
    actor_rollout_ref.actor.use_kl_loss=true \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size=4 \
    actor_rollout_ref.actor.fsdp_config.param_offload=true \
    actor_rollout_ref.actor.fsdp_config.grad_offload=true \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=true \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=6 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.35 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=64 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    algorithm.no_think_rl=false \
    actor_rollout_ref.rollout.n_agent=8 \
    actor_rollout_ref.rollout.temperature=0.2 \
    actor_rollout_ref.actor.state_masking=true \
    trainer.logger=['wandb'] \
    +trainer.val_only=false \
    +trainer.val_before_train=true \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=6 \
    trainer.nnodes=1 \
    trainer.save_freq=100 \
    trainer.test_freq=50 \
    trainer.project_name=$WAND_PROJECT \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.total_epochs=5 \
    trainer.total_training_steps=300\
    trainer.default_hdfs_dir=null \
    trainer.default_local_dir=verl_checkpoints/$EXPERIMENT_NAME \
    reward_model.structure_format_score=0.2 \
    reward_model.final_format_score=0.1 \
    reward_model.retrieval_score=0.2 \
    reward_model.cover_exact_score=0.4 \
    reward_model.invalid_action_penalty=2.0 \
    reward_model.repeated_invalid_penalty=0.0 \
    reward_model.empty_answer_penalty=0.5 \
    reward_model.valid_search_bonus=0.0 \
    reward_model.first_search_bonus=0.2 \
    reward_model.generic_search_penalty=0.8 \
    reward_model.instruction_completion_penalty=1.0 \
    reward_model.answer_format_penalty=0.8 \
    reward_model.no_search_wrong_penalty=0.0 \
    reward_model.invalid_format_penalty=0.4 \
    reward_model.no_action_penalty=0.6 \
    reward_model.symptoms_only_penalty=0.5 \
    reward_model.overlong_answer_penalty=0.3 \
    reward_model.copied_answer_penalty=0.4 \
    reward_model.repeated_same_query_penalty=0.2 \
    reward_model.answer_before_search_penalty=0.3 \
    reward_model.extra_search_penalty=0.1 \
    reward_model.answer_max_words=24 \
    reward_model.answer_max_chars=160 \
    reward_model.format_scale_start=1.0 \
    reward_model.format_scale_end=0.25 \
    reward_model.format_scale_steps=300 \
    max_turns=4 \
    max_invalid_actions=4 \
    data.terminate_on_observation_overflow=true \
    retriever.url="http://127.0.0.1:${RETRIEVER_PORT}/retrieve" \
    retriever.topk=3 \
    retriever.max_result_chars=1200 \
    2>&1 | tee $EXPERIMENT_NAME.log
